# Generated by Django 2.2.7 on 2019-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
