# Generated by Django 2.2.5 on 2019-11-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='fullname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
