# Generated by Django 2.2.5 on 2019-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20191103_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fullname',
            field=models.CharField(blank='True', max_length=25, null='True'),
        ),
    ]
