# Generated by Django 2.2.5 on 2019-11-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20191104_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggedin', models.BooleanField(default='False')),
            ],
        ),
    ]
