# Generated by Django 2.2.7 on 2019-11-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20191107_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
