# Generated by Django 2.2.7 on 2019-11-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20191115_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
