# Generated by Django 2.2.7 on 2019-11-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
