# Generated by Django 2.2.7 on 2019-11-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_ordered',
        ),
    ]
