# Generated by Django 2.2.7 on 2019-11-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20191124_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='is_ordered',
        ),
    ]
