# Generated by Django 2.2.7 on 2019-12-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20191209_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='owner',
        ),
    ]
