# Generated by Django 2.2.7 on 2019-12-10 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_cartitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
