# Generated by Django 2.2.7 on 2019-12-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_cartitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='owner',
        ),
    ]
