# Generated by Django 2.2.7 on 2019-12-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_auto_20191214_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='cart.Order'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=1000),
        ),
    ]
