# Generated by Django 2.2.7 on 2019-12-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_auto_20191214_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
