# Generated by Django 2.2.7 on 2019-12-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_cartitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cart.CartItem'),
        ),
    ]
