# Generated by Django 2.2.5 on 2019-12-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_auto_20191226_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='owner',
        ),
    ]
