# Generated by Django 2.2.5 on 2019-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_remove_cartitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cart',
            field=models.BooleanField(default=True),
        ),
    ]
