# Generated by Django 2.2.7 on 2019-11-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191121_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='product_pics'),
        ),
    ]
