# Generated by Django 2.2.5 on 2019-12-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191209_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(default='common', max_length=100),
        ),
    ]
