# Generated by Django 2.2.5 on 2019-12-30 15:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('products', '0007_auto_20191230_1523'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogary',
            new_name='Catagory',
        ),
    ]
