# Generated by Django 2.2.5 on 2019-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191230_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catagory',
        ),
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(default='common', max_length=100),
        ),
    ]
