# Generated by Django 2.2.5 on 2019-12-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191230_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='name',
        ),
    ]
