# Generated by Django 2.2.5 on 2019-12-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_catagory_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Catagories'},
        ),
        migrations.AddField(
            model_name='catagory',
            name='name',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
