# Generated by Django 2.2.5 on 2019-12-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191230_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=True, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=12, max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='untitled', max_length=50),
        ),
    ]
