# Generated by Django 2.2.5 on 2019-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20191230_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='untitled', max_length=50, null=True),
        ),
    ]
