# Generated by Django 2.2.5 on 2019-12-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catagory',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='untitled', max_length=50),
        ),
    ]
