# Generated by Django 2.2.5 on 2019-12-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20191230_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availability',
            new_name='catagory',
        ),
    ]
